### ISSUE TITLE
wrong directory path to COLCON_IGNORE marker file?

### ISSUE THREAD

**Issue by Karsten1987** [ros2/ci#363] opened 2020-01-09 00:34 UTC
I've seen my test failing with the following error message:

```
16:29:32 FileNotFoundError: [Errno 2] No such file or directory: 'src/src/ros2/common_interfaces/actionlib_msgs/COLCON_IGNORE'
```

Printing the individual variables such as `package_name` and `package_path` reveal a duplicate `src` string within the path. I suppose that removing the first `src` would help that. https://github.com/ros2/ci/blob/25a3bdf20a310b1df8b28a5af92e1eb66d5681ea/ros2_batch_job/__main__.py#L715

```
16:29:32 package_name action_msgs
16:29:32 package_path src/ros2/rcl_interfaces/action_msgs
16:29:32 args sourcespace src
16:29:32 package_name action_tutorials_cpp
16:29:32 package_path src/ros2/demos/action_tutorials/action_tutorials_cpp
....
```

any idea why this occurring right now?

**Comment by Karsten1987** [comment] 2020-01-09 00:40
In fact, not only the COLCON_IGNORE markers have changed, also the actually compilation fails:

```
16:36:37 Failed   <<< ament_package	[ Exited with code 1 ]
16:36:37 Traceback (most recent call last):
16:36:37   File "<string>", line 1, in <module>
16:36:37   File "/Users/osrf/jenkins-agent/workspace/ci_osx/venv/lib/python3.7/site-packages/colcon_python_setup_py/package_identification/python_setup_py.py", line 111, in get_setup_arguments
16:36:37     runpy.run_path(str(setup_py))
16:36:37   File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 261, in run_path
16:36:37     code, fname = _get_code_from_file(run_name, path_name)
16:36:37   File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 231, in _get_code_from_file
16:36:37     with open(fname, "rb") as f:
16:36:37 FileNotFoundError: [Errno 2] No such file or directory: 'src/ament/ament_lint/ament_lint/setup.py'
```

**Comment by dirk-thomas** [comment] 2020-01-09 01:22
Duplicate of colcon/colcon-python-setup-py#29.

**Comment by dirk-thomas** [comment] 2020-01-09 02:17
The referenced PR only addresses the problem from the second comment.

**Closed** 2020-01-09 02:21 UTC
Labels: bug, duplicate
