### ISSUE TITLE
Packaging OSX build host is using out of date version of class_loader from homebrew 

### ISSUE THREAD

**Issue by emersonknapp** [ros2/ci#456] opened 2020-05-20 22:00 UTC
In latest OSX packaging builds, e.g. https://ci.ros2.org/view/packaging/job/packaging_osx/1854/consoleFull 

```
03:45:10 console_bridge 0.4.4
```

The console_bridge version installed via homebrew does not match the version available since https://github.com/Homebrew/homebrew-core/commit/7afc7e651181835463cf6a34083f0e1d4ff55c5d

So when I `brew install console_bridge`, I get

```
2:52:19 ➜  master git:(master) ✗ brew info console_bridge                                                                                                                                                                                 5s
console_bridge: stable 0.5.0 (bottled)
Robot Operating System-independent package for logging
https://wiki.ros.org/console_bridge/
/usr/local/Cellar/console_bridge/0.5.0 (13 files, 41.4KB) *
  Poured from bottle on 2020-05-18 at 17:25:03
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/console_bridge.rb
==> Dependencies
Build: cmake ✔
==> Analytics
install: 1,107 (30 days), 2,738 (90 days), 8,917 (365 days)
install-on-request: 190 (30 days), 438 (90 days), 1,489 (365 days)
build-error: 0 (30 days)
```

After downloading that packaged build to use, `rqt` binary attempts to

```
load ImportError: dlopen(/Users/snehaldb/ros2_foxy/ros2-osx/lib/python3.8/site-packages/qt_gui_cpp/libqt_gui_cpp_sip.so, 2): Library not loaded: /usr/local/opt/console_bridge/lib/libconsole_bridge.0.4.dylib
```

Because the library installed there is `libconsole_bridge.0.5.dylib` now. Can't use the packaged builds.

**Comment by clalancette** [comment] 2020-05-20 22:10
Yeah, it is wrapped up in https://github.com/ros2/console_bridge_vendor/pull/9 .  Unfortunately, I'm still running into trouble making that work.  But with the work we did elsewhere, I'm hoping I can put something together that makes it work on all platforms.

**Comment by emersonknapp** [comment] 2020-05-20 22:30
Is this actually related to that relocatability? It seems like the problem here is just that the build machine  has an outdated of the package, that we don't have access to any more because console_bridge brew package does not have legacy versions.

**Comment by clalancette** [comment] 2020-05-21 01:02
> Is this actually related to that relocatability? It seems like the problem here is just that the build machine has an outdated version of the package, that we don't have access to any more because console_bridge brew package does not have legacy versions.

Its related because updating to 0.5.0 actually seems to break the build on macOS.  I still need to debug further to figure out why the build machines aren't affected by this.

**Comment by emersonknapp** [comment] 2020-05-21 01:03
Oh, yes, that's true, and the build breakage seems to be around failing to find the console_bridge/console.h header.

I don't see the build job doing a `brew install` command, so maybe it's just that the dependencies haven't been installed in the last two weeks on the build machines? (0.5.0 released 13 days ago)

**Comment by clalancette** [comment] 2020-05-21 01:08
> I don't see the build job doing a `brew install` command, so maybe it's just that the dependencies haven't been installed in the last two weeks on the build machines? (0.5.0 released 13 days ago)

Right, macOS is our least reproducible build; CI just builds against whatever happens to be the last time someone did `brew upgrade` on the CI machines.  It happens that I did a `brew upgrade` on all of our CI machines like 10 days ago, and in theory they all have console_bridge 0.5.0 installed.  But there seem to be some vestiges of 0.4.4 left, which I'm guessing is why it works there.  On my local macOS machine, where I don't have that history, just installing 0.5.0 does not work for me.  Similarly, upgrading the `console_bridge_vendor` to 0.5.0 also does not work for me on macOS.

**Comment by jacobperron** [comment] 2020-05-28 17:57
@emersonknapp @clalancette I think this issue has been resolved with the latest release of console_bridge, can you confirm?

**Comment by emersonknapp** [comment] 2020-05-28 20:21
Verified that the latest fat binary archives can successfully run e.g. demo_nodes_cpp, because it finds the 0.5 console_bridge that brew installs.

**Closed** 2020-05-28 21:47 UTC
