### ISSUE TITLE
CI swallows Python deprecation warnings

### ISSUE THREAD

**Issue by rotu** [ros2/ci#430] opened 2020-04-13 22:04 UTC
Deprecation warnings found in CI are not reported on the run overview; https://ci.ros2.org/view/nightly/job/nightly_win_deb/1589/

This applies to both warnings found when running pytest tests:
```
26: Test command: C:\Python37\python_d.exe "-u" "C:/ci/ws/install/share/ament_cmake_test/cmake/run_test.py" "C:/ci/ws/build/rclpy/test_results/rclpy/test_task.xunit.xml" "--package-name" "rclpy" "--output-file" "C:/ci/ws/build/rclpy/ament_cmake_pytest/test_task.txt" "--append-env" "AMENT_PREFIX_PATH=C:/ci/ws/build/rclpy/ament_cmake_index" "PYTHONPATH=C:/ci/ws/build/rclpy" "--command" "C:/Python37/python_d.exe" "-u" "-m" "pytest" "C:/ci/ws/src/ros2/rclpy/rclpy/test/test_task.py" "-o" "cache_dir=C:/ci/ws/build/rclpy/ament_cmake_pytest/test_task/.cache" "--junit-xml=C:/ci/ws/build/rclpy/test_results/rclpy/test_task.xunit.xml" "--junit-prefix=rclpy" "-We"
26: Test timeout computed to be: 120
26: -- run_test.py: extra environment variables to append:
26:  - AMENT_PREFIX_PATH+=C:/ci/ws/build/rclpy/ament_cmake_index
26:  - PYTHONPATH+=C:/ci/ws/build/rclpy
26: -- run_test.py: invoking following command in 'C:\ci\ws\build\rclpy':
26:  - C:/Python37/python_d.exe -u -m pytest C:/ci/ws/src/ros2/rclpy/rclpy/test/test_task.py -o cache_dir=C:/ci/ws/build/rclpy/ament_cmake_pytest/test_task/.cache --junit-xml=C:/ci/ws/build/rclpy/test_results/rclpy/test_task.xunit.xml --junit-prefix=rclpy -We
26: Warning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
26: Warning: TerminalReporter.writer attribute is deprecated, use TerminalReporter._tw instead at your own risk.
26: See https://docs.pytest.org/en/latest/deprecations.html#terminalreporter-writer for more information.
```

And when building packages:
```
Starting >>> test_launch_ros
c:\python37\lib\site-packages\colcon_ros\task\ament_python\build.py:86: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  .format_map(locals()))
[5274.624s] colcon.colcon_ros.task.ament_python.build WARNING Package 'test_launch_ros' doesn't explicitly install a marker in the package index (colcon-ros currently does it implicitly but that fallback will be removed in the future)
```

**Comment by dirk-thomas** [comment] 2020-04-13 22:41
This looks like a duplicate of #418.

**Closed by dirk-thomas** 2020-04-13 22:41 UTC
